name: Deploy Backend - Multi-Stage (dev, qa, prod)


on:
 push:
   branches:
     - dev
     - qa
     - main


jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3


     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18'


     - name: Install dependencies
       run: npm ci


     - name: Build application
       run: npm run build


     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2


     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


     - name: Build and Push Docker Image
       uses: docker/build-push-action@v5
       id: docker_build
       with:
         context: .
         file: ./Dockerfile
         push: true
         build-args: |
           ENV_TYPE=${{ github.ref_name }}
           PORT=${{ env.PORT }}
         tags: |
           ${{ secrets.DOCKER_HUB_USERNAME }}/your-backend:${{ github.ref_name }}


     - name: Deploy to EC2 via SSH
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.EC2_IP }}
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           # Navigate to app directory
           cd /home/ubuntu/backend


           echo "Stopping existing container if any..."
           docker stop backend-${{ github.ref_name }} || true
           docker rm backend-${{ github.ref_name }} || true


           echo "Pulling latest image..."
           docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/your-backend:${{ github.ref_name }}


           echo "Deploying new version..."
           docker run -d \
             --name backend-${{ github.ref_name }} \
             -p ${{ env.PORT }}:${{ env.PORT }} \
             -e MYSQL_HOST=mysql-${{ github.ref_name }} \
             -e MYSQL_PORT=3306 \
             -e MYSQL_USER=${{ github.ref_name }}_user \
             -e MYSQL_PASSWORD=Asher976123@ \
             -e MYSQL_DB=myapp_${{ github.ref_name }} \
             ${{ secrets.DOCKER_HUB_USERNAME }}/your-backend:${{ github.ref_name }}
